const mockEvents = {
  city: {
    id: 28401,
    city: 'Wilmington',
    lat: 34.23,
    lon: -77.94,
    state: 'NC',
    country: 'us',
    zip: '28401',
    member_count: 6046,
  },
  events: [
    {
      created: 1595713891000,
      duration: 7200000,
      id: '272152632',
      name: '5 mile beach walk with appropriate social distancing!',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596466800000,
      local_date: '2020-08-03',
      local_time: '11:00',
      rsvp_open_offset: 'PT232H',
      rsvp_close_offset: 'PT1H',
      updated: 1595988783000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1588762070000,
        name: 'Carolina Beach Walk & Roll Adventures',
        id: 33694610,
        join_mode: 'approval',
        lat: 34.13999938964844,
        lon: -77.91999816894531,
        urlname: 'Wilmington-Nature-Walks-Meetup-Group',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Wilmington-Nature-Walks-Meetup-Group/events/272152632/',
      description: '<p>A beautiful 5 mile beach walk! I walk at the waters edge and carry my flip-flops, wearing shorts or a bathing suit to catch some rays!</p> <p>Free parking available on request. Will stay afterwards and get lunch if you like.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '08:00',
      local_date: '2020-08-01',
      link: 'https://www.meetup.com/Wilmington-Hiking-and-Outdoor-Activities/events/271921428/',
      visibility: 'public_limited',
      group: {
        created: 1530315463000,
        name: 'Wilmington Hiking and Outdoor Adventures',
        id: 29038312,
        join_mode: 'open',
        lat: 34.13999938964844,
        lon: -77.91999816894531,
        urlname: 'Wilmington-Hiking-and-Outdoor-Activities',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 15,
      duration: 14400000,
      time: 1596283200000,
      utc_offset: -14400000,
      name: 'Paddle Cape Fear River ',
      id: '271921428'
    },
    {
      created: 1568831804000,
      duration: 2700000,
      id: 'glbfjrybckbnc',
      name: 'Ballroom @Wilmington Ballroom (WB)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596150900000,
      local_date: '2020-07-30',
      local_time: '19:15',
      updated: 1568831804000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26455829,
        name: 'Wilmington Ballroom',
        lat: 34.20945358276367,
        lon: -77.85160064697266,
        repinned: true,
        address_1: '5629 Oleander Dr #110',
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28403',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1560471510000,
        name: 'Dance Wilmington',
        id: 32168883,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94000244140625,
        urlname: 'dancewilmington-nc',
        who: 'Dancers',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/dancewilmington-nc/events/glbfjrybckbnc/',
      description: '<p>Ballroom (various) walk-in classes (check website calendar)</p> <p>$15 - every Tuesday/Thursday</p> <p>Wilmington Ballroom<br/><a href=\'https://www.wilmingtonballroom.com/upcoming-dance-programs.html\' class=\'linkified\'>https://www.wilmingtonballroom.com/upcoming-dance-programs.html</a></p> <p>***REMEMBER TO CHECK A GROUP\'S WEBSITE (provided) BEFORE ATTENDING AN EVENT, IN CASE OF CHANGES TO THE EVENT!! This group is dependent upon member communication to maintain its accuracy and usefulness. If you become aware of a change to an event, please let us know!***</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1568831828000,
      duration: 6360000,
      id: 'llbfjrybckbpc',
      name: 'Ballroom @Wilmington Ballroom (WB)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596237300000,
      local_date: '2020-07-31',
      local_time: '19:15',
      updated: 1568831828000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1560471510000,
        name: 'Dance Wilmington',
        id: 32168883,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94000244140625,
        urlname: 'dancewilmington-nc',
        who: 'Dancers',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/dancewilmington-nc/events/llbfjrybckbpc/',
      description: '<p>FREE - every Friday</p> <p>7:15-8:30 Dance Social</p> <p>Wilmington Ballroom<br/><a href=\'https://www.wilmingtonballroom.com/upcoming-dance-programs.html\' class=\'linkified\'>https://www.wilmingtonballroom.com/upcoming-dance-programs.html</a></p> <p>***REMEMBER TO CHECK A GROUP\'S WEBSITE (provided) BEFORE ATTENDING AN EVENT, IN CASE OF CHANGES TO THE EVENT!! This group is dependent upon member communication to maintain its accuracy and usefulness. If you become aware of a change to an event, please let us know!***</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '20:00',
      local_date: '2020-07-30',
      link: 'https://www.meetup.com/Wilmington-X-Ball-Meetup/events/qqlwglybckbnc/',
      visibility: 'public_limited',
      group: {
        created: 1430920781000,
        name: 'Wilmington \'X- Ball\' Group',
        id: 18578890,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94000244140625,
        urlname: 'Wilmington-X-Ball-Meetup',
        who: 'X-baller',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 1,
      duration: 5400000,
      time: 1596153600000,
      utc_offset: -14400000,
      name: 'Wilmington Danney-ball',
      id: 'qqlwglybckbnc'
    },
    {
      created: 1506397440000,
      duration: 3600000,
      id: 'tghxtnybclbgb',
      name: 'Please join us for a fun-filled morning of  prepared 5 to 7 min speeches',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596538800000,
      local_date: '2020-08-04',
      local_time: '07:00',
      updated: 1506397440000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 3658392,
        name: 'Chris\'s Restaurant',
        lat: 34.22639083862305,
        lon: -77.92577362060547,
        repinned: false,
        address_1: '853 South 17th Street',
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28403',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1506395988000,
        name: 'Wilmington Toastmasters Meetup',
        id: 26054938,
        join_mode: 'open',
        lat: 34.15999984741211,
        lon: -77.87000274658203,
        urlname: 'meetup-group-UFNsJzlF',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/meetup-group-UFNsJzlF/events/tghxtnybclbgb/',
      description: '<p>We meet for 1 hour to inprove our public speaking skills, Following Toastmaster International structure, Guest are always welcome. enjoy the best breakfast in town while enjoying short prepared speeches as well as impromptu public speaking any questions please call or text[masked]</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1595639156000,
      duration: 7200000,
      id: 'xdqrvrybckbnc',
      name: 'Devine Audacity Book Group',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596146400000,
      local_date: '2020-07-30',
      local_time: '18:00',
      updated: 1595639159000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25284143,
        name: 'Unity of Wilmington',
        lat: 34.22574234008789,
        lon: -77.9029769897461,
        repinned: false,
        address_1: '717 Orchard Avenue',
        city: 'Wilmington',
        country: 'US',
        localized_country_name: 'USA'
      },
      is_online_event: false,
      group: {
        created: 1496611593000,
        name: 'Unity Wilmington',
        id: 24279262,
        join_mode: 'open',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Unity-Wilmington',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Unity-Wilmington/events/xdqrvrybckbnc/',
      description: '<p>This online book group meets Thursdays through August 20 at 6:00 pm.<br/>Linda Martella-Whitsett\'s book makes the audacious claim that each of us can be \'the light of the world\' Jesus instructed his followers to be. She offers a path for living a deep and authentic life outside of the strictures of traditional religious categories. A refreshing approach, in essence, on how to be spiritual without being religious.<br/>Let your light shine!<br/>Please email the facilitators Rev. Mindy Tucker [masked]<br/>or Rev. Nickie Golden [masked] for sign-on information.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1594653751000,
      duration: 12600000,
      fee: {
        accepts: 'paypal',
        amount: 150,
        currency: 'USD',
        description: '',
        label: 'Price',
        required: true
      },
      id: '271899705',
      name: 'Reiki I Certification Class, Energy Medicine',
      rsvp_limit: 8,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596286800000,
      local_date: '2020-08-01',
      local_time: '09:00',
      rsvp_close_offset: 'PT18H',
      updated: 1595444072000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 18929762,
        name: 'Crossroads Center - Channel for Healing',
        lat: 34.22071838378906,
        lon: -77.88689422607422,
        repinned: true,
        address_1: '890 S. Kerr Ave., Suite 260',
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28403',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1276024001000,
        name: 'Wilmington, Leland & Brunswick County Energy Work',
        id: 1658021,
        join_mode: 'approval',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Wilmington-Energy-Work',
        who: 'Seekers, Healers & Lightworkers',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Wilmington-Energy-Work/events/271899705/',
      description: '<p>Reiki I Certification</p> <p>Date: Saturday, August 1, 2020<br/>Time: 9:00 AM -12:30 PM<br/>Fee: $150.00 * prepayment is required<br/>Location: 890 S Kerr Ave., Suite 260, Wilmington, NC 28403</p> <p>Snacks &amp; Material Provided</p> <p>The word Reiki is made of two Japanese words – Rei which means \'Universal Wisdom or the Higher Power\' and Ki which is \'life force energy\'. So Reiki is actually \'spiritually guided life force energy.\'</p> <p>You will learn:<br/>Reiki History<br/>Training in hand positions<br/>Initiated into the first sacred symbol and a lot more.<br/>We will have time for individual practice on one another.</p> <p>Please contact me for further information by emailing me at: [masked].</p> <p>About this Meetup Group (<a href=\'http://www.meetup.com/Wilmington-Reiki-Share-Energy-Work/about/\' class=\'linkified\'>http://www.meetup.com/Wilmington-Reiki-Share-Energy-Work/about/</a>)</p> ',
      how_to_find_us: 'Channel for Healing- Upstairs - Pat 910-274-1716',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '18:30',
      local_date: '2020-08-01',
      link: 'https://www.meetup.com/Wilmington-Women/events/271821507/',
      visibility: 'public_limited',
      group: {
        created: 1264711707000,
        name: 'Women of Wilmington',
        id: 1590387,
        join_mode: 'approval',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Wilmington-Women',
        who: 'Wilmington Women',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 5,
      duration: 7200000,
      time: 1596321000000,
      utc_offset: -14400000,
      name: 'Kilbeggan Irish Band at the hoplite',
      id: '271821507'
    },
    {
      created: 1594340983000,
      duration: 7200000,
      id: 'tqpfvrybclbdb',
      name: 'A Course in Miracles on Zoom ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596409200000,
      local_date: '2020-08-02',
      local_time: '19:00',
      updated: 1594340983000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25284143,
        name: 'Unity of Wilmington',
        lat: 34.22574234008789,
        lon: -77.9029769897461,
        repinned: false,
        address_1: '717 Orchard Avenue',
        city: 'Wilmington',
        country: 'US',
        localized_country_name: 'USA'
      },
      is_online_event: false,
      group: {
        created: 1496611593000,
        name: 'Unity Wilmington',
        id: 24279262,
        join_mode: 'open',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Unity-Wilmington',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Unity-Wilmington/events/tqpfvrybclbdb/',
      description: '<p>A Course in Miracles on Zoom<br/>Sundays and Wednesdays @ 7:00pm<br/>Please contact Kate Martin at<br/>[masked] or phone (910)[masked]<br/>Anyone interested is welcome to join the group for<br/>reading and discussion of the text.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1595714247000,
      duration: 7200000,
      id: '272152681',
      name: '5 mile beach walk with appropriate social distancing!',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596207600000,
      local_date: '2020-07-31',
      local_time: '11:00',
      rsvp_open_offset: 'PT232H',
      rsvp_close_offset: 'PT1H',
      updated: 1595714247000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1588762070000,
        name: 'Carolina Beach Walk & Roll Adventures',
        id: 33694610,
        join_mode: 'approval',
        lat: 34.13999938964844,
        lon: -77.91999816894531,
        urlname: 'Wilmington-Nature-Walks-Meetup-Group',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Wilmington-Nature-Walks-Meetup-Group/events/272152681/',
      description: '<p>A beautiful 5 mile beach walk! I walk at the waters edge and carry my flip-flops, wearing shorts or a bathing suit to catch some rays!</p> <p>Free parking available on request. Will stay afterwards and get lunch if you like.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '17:30',
      local_date: '2020-08-03',
      link: 'https://www.meetup.com/volunteerwilmington-nc/events/frggkrybclbfb/',
      visibility: 'public_limited',
      group: {
        created: 1558040039000,
        name: 'Volunteer Wilmington',
        id: 31925889,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94000244140625,
        urlname: 'volunteerwilmington-nc',
        who: 'Volunteers',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 1,
      duration: 7200000,
      time: 1596490200000,
      utc_offset: -14400000,
      name: 'Vintage Values Sorting Party',
      id: 'frggkrybclbfb'
    },
    {
      created: 1528108717000,
      duration: 7200000,
      id: 'xpkmtpybclbfb',
      name: 'Healing Night First Monday of Each Month Unity Church 717 Orchard Wilmington NC',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596495600000,
      local_date: '2020-08-03',
      local_time: '19:00',
      updated: 1528108717000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 1548103,
        name: 'Unity of Wilmington Church',
        lat: 34.22569274902344,
        lon: -77.90301513671875,
        repinned: false,
        address_1: '717 Orchard Ave.',
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28403',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1286160410000,
        name: 'Healing Arts in the Wilmington Healing Community',
        id: 1716659,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94999694824219,
        urlname: 'Healing-Arts-Wilmington-Healing-Community',
        who: 'Empowered Healers',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Healing-Arts-Wilmington-Healing-Community/events/xpkmtpybclbfb/',
      why: 'Healing of the body… Healing of the soul… Healing for relationship… Healing for business… Healing of the pain… Healing of the fear… The PATH to SUCCESS… The CALL for LOVE…',
      description: '<p>Healing Night - First Monday of every month at 7:00 p.m.</p> <p>This evening of healing (on the First Monday of each month except July or August) and is open to all wishing to receive healing touch.</p> <p>Please Contact Sis Tyler at[masked] - to confirm Event or if you have any questions or if you wish to participate as a healer.</p> <p>Please check at <a href=\'http://www.unitywil.com/events\' class=\'linkified\'>http://www.unitywil.com/events</a></p> <p>Reiki practioners meet on the last Monday of the month.</p> <p>Healing of the body… Healing of the soul…</p> <p>Healing for relationship… Healing for business…</p> <p>Healing of the pain… Healing of the fear…</p> <p>The PATH to SUCCESS… The CALL for LOVE…</p> <p>These are FREE Events - Donations are Welcomed (with no obligations)</p> <p>Note from Valentina:</p> <p>I am not the one who is hosting this event - and at this time I might even will NOTbe able to be therein person - to offer healing touch to the ones who will be there.</p> <p>But I am always there in Spirit with you guys in Unity!</p> <p>***</p> <p>Suzyn Walsh: Valentina Medical Intuitive</p> <p>\'How I Received Healing Light-Energy From Valentina</p> <p>A True Story\'</p> <p>by Suzyn Walsh, Quantum Bioneer</p> <p><a href=\'http://www.suzynwalsh.com/id4.html\' class=\'linkified\'>http://www.suzynwalsh.com/id4.html</a></p> <p>Calling all healers! Medical Intuitive Valentina Borodina coming to town</p> <p><a href=\'http://www.examiner.com/spirituality-in-denver/calling-all-healers-medical-intuitive-valentina-borodina-coming-to-town\' class=\'linkified\'>http://www.examiner.com/spirituality-in-denver/calling-all-healers-medical-intuitive-valentina-borodina-coming-to-town</a></p> <p>Valentina\'s Blog</p> <p><a href=\'http://networkedblogs.com/8OqG8\' class=\'linkified\'>http://networkedblogs.com/8OqG8</a></p> ',
      how_to_find_us: 'We will be at The Sanctuary. Please be sure to Contact Sis Tyler at 452-0415 - to confirm Event',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1594654166000,
      duration: 16200000,
      fee: {
        accepts: 'paypal',
        amount: 175,
        currency: 'USD',
        description: '',
        label: 'Price',
        required: true
      },
      id: '271899809',
      name: 'Reiki II Certification Class, Energy Medicine',
      rsvp_limit: 8,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596301200000,
      local_date: '2020-08-01',
      local_time: '13:00',
      rsvp_close_offset: 'PT22H',
      updated: 1595444202000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 18929762,
        name: 'Crossroads Center - Channel for Healing',
        lat: 34.22071838378906,
        lon: -77.88689422607422,
        repinned: true,
        address_1: '890 S. Kerr Ave., Suite 260',
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28403',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1276024001000,
        name: 'Wilmington, Leland & Brunswick County Energy Work',
        id: 1658021,
        join_mode: 'approval',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Wilmington-Energy-Work',
        who: 'Seekers, Healers & Lightworkers',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Wilmington-Energy-Work/events/271899809/',
      description: '<p>Reiki II Certification Class<br/>Date: Saturday, August 1, 2020<br/>Time: 1:00 to 5:30 PM **requirement Reiki I<br/>Cost: $175.00 *prepayment is required<br/>Location: 890 S Kerr Ave., Suite 260, Wilmington, NC 28403</p> <p>Usui - Ryoho Reiki.<br/>Join us for this powerful form of Reiki.</p> <p>Snacks &amp; Manual provided.</p> <p>You will learn &amp; Review:<br/>Reiki History<br/>Hand Positions<br/>Reiki I *prior certification is required<br/>Initiated into the Reiki II Sacred Symbols<br/>How to use these symbols</p> <p>Protection, grounding, working energy and preparing healing/long distance grids.</p> <p>*We will have time for individual practice on one another.</p> <p>This is an exciting, rewarding experience.</p> <p>You may sign up here, my website Channel for Healing (<a href=\'http://www.channelforhealing.com\' class=\'linkified\'>http://www.channelforhealing.com</a>) or call[masked]</p> ',
      how_to_find_us: 'Channel for Healing- Upstairs - Pat 910-274-1716',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1595714265000,
      duration: 7200000,
      id: '272152685',
      name: '5 mile beach walk with appropriate social distancing!',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596380400000,
      local_date: '2020-08-02',
      local_time: '11:00',
      rsvp_open_offset: 'PT232H',
      rsvp_close_offset: 'PT1H',
      updated: 1595714297000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1588762070000,
        name: 'Carolina Beach Walk & Roll Adventures',
        id: 33694610,
        join_mode: 'approval',
        lat: 34.13999938964844,
        lon: -77.91999816894531,
        urlname: 'Wilmington-Nature-Walks-Meetup-Group',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Wilmington-Nature-Walks-Meetup-Group/events/272152685/',
      description: '<p>A beautiful 5 mile beach walk! I walk at the waters edge and carry my flip-flops, wearing shorts or a bathing suit to catch some rays!</p> <p>Free parking available on request. Will stay afterwards and get lunch if you like.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1595451138000,
      duration: 7200000,
      fee: {
        accepts: 'cash',
        amount: 1,
        currency: 'USD',
        description: '',
        label: 'Price',
        required: false
      },
      id: 'mcgqvrybckbpc',
      name: 'Open Film forum ',
      rsvp_limit: 25,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596236400000,
      local_date: '2020-07-31',
      local_time: '19:00',
      updated: 1595451149000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26923245,
        name: 'Summer Hills',
        lat: 34.206886291503906,
        lon: -77.94278717041016,
        repinned: false,
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28401',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1589639035000,
        name: 'Rhodywood Wilmington NC Indie Filmmaking Meetup Group',
        id: 33724057,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94000244140625,
        urlname: 'RHODYWOOD-Wilmington-NC-Indie-Filmmaking-Meetup-Group',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/RHODYWOOD-Wilmington-NC-Indie-Filmmaking-Meetup-Group/events/mcgqvrybckbpc/',
      description: '<p>This is an open forum{ LIVE ON SITE) for filmmakers, actors, cast/crew to get together to discuss how this crisis has changed the way we must do business.<br/>If you have any idea or want to show a short film etc. please message Anthony Demings on facebook or [masked]</p> ',
      how_to_find_us: 'Were located at 1919 Carolina Beach Road, 3 blocks south of Greenfield lake, Wilmington NC ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1594342719000,
      duration: 7200000,
      id: 'pvpfvrybckbpc',
      name: 'Words of Wisdom Book Group Online Zoom Meetings',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596209400000,
      local_date: '2020-07-31',
      local_time: '11:30',
      updated: 1594342719000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25284143,
        name: 'Unity of Wilmington',
        lat: 34.22574234008789,
        lon: -77.9029769897461,
        repinned: false,
        address_1: '717 Orchard Avenue',
        city: 'Wilmington',
        country: 'US',
        localized_country_name: 'USA'
      },
      is_online_event: false,
      group: {
        created: 1496611593000,
        name: 'Unity Wilmington',
        id: 24279262,
        join_mode: 'open',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Unity-Wilmington',
        who: 'Members',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Unity-Wilmington/events/pvpfvrybckbpc/',
      description: '<p>Words of Wisdom Book Group Online Zoom Meetings</p> <p>New time: 11:30 to 1:15 every Friday.</p> <p>Currently, the book club is studying<br/>The 12 Spiritual Laws of the Universe<br/>on Zoom with Al Sica leading the discussion.<br/>Please contact him at: [masked] for information on how to get on the zoom call.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1583330898000,
      duration: 7200000,
      id: 'vxvfqrybclbfb',
      name: 'Who\'s ready for some cribbage fun??  Let\'s play!!',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596492000000,
      local_date: '2020-08-03',
      local_time: '18:00',
      updated: 1583330898000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 0,
      venue: {
        id: 25157447,
        name: 'Carolina Ale House',
        lat: 34.23585510253906,
        lon: -77.8724594116211,
        repinned: true,
        address_1: '317-c South College Road',
        city: 'Wilmington',
        country: 'us',
        localized_country_name: 'USA',
        zip: '28403',
        state: 'NC'
      },
      is_online_event: false,
      group: {
        created: 1458929205000,
        name: 'Cape Fear Cribbage Crazy',
        id: 19756865,
        join_mode: 'open',
        lat: 34.22999954223633,
        lon: -77.94999694824219,
        urlname: 'Wilmington-Cribbage-Crazy',
        who: 'Players',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      link: 'https://www.meetup.com/Wilmington-Cribbage-Crazy/events/vxvfqrybclbfb/',
      description: '<p>We will now meet every Monday night at 6pm.</p> <p>The Carolina Ale House has been an excellent Meet up spot. We hope to see you there.</p> <p>Many of us bring cards and boards. Feel free to bring yours as well.</p> ',
      how_to_find_us: 'Cribbage boards and smiles!',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      local_time: '14:00',
      local_date: '2020-08-04',
      link: 'https://www.meetup.com/Wilmington-Women/events/272233604/',
      visibility: 'public_limited',
      group: {
        created: 1264711707000,
        name: 'Women of Wilmington',
        id: 1590387,
        join_mode: 'approval',
        lat: 34.20000076293945,
        lon: -77.87999725341797,
        urlname: 'Wilmington-Women',
        who: 'Wilmington Women',
        localized_location: 'Wilmington, NC',
        state: 'NC',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern'
      },
      waitlist_count: 0,
      yes_rsvp_count: 1,
      duration: 7200000,
      time: 1596564000000,
      utc_offset: -14400000,
      name: 'Let\'s play mahjong',
      id: '272233604'
    },
  ],
};

export { mockEvents };
